**Instanciando Tensores e Tipos de Tensores**

In [37]:
#Instanciando tensores a partir de listas

import torch

lista = [[1,2,3],[4,5,6]]

#Tensor comum
tns = torch.Tensor(lista)
print(tns.dtype) #Float32
print(tns)

#Mesma coisa do primeiro porém com instanciação float de forma explícita
tns = torch.FloatTensor(lista)
print(tns.dtype) #Float32
print(tns)


#Tensor float64 ponto flutuante de maior precisão
tns = torch.DoubleTensor(lista)
print(tns.dtype) #Float64
print(tns)

#Tensor para trabalhar com inteiros, em geral é utilizado o long 
tns = torch.LongTensor(lista)
print(tns.dtype) #Int64
print(tns)


torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])


In [38]:
#Instanciando tensores a partir de arrays numpy
import numpy as np

arr = np.random.rand(3,4)

#convertendo o array numpy em tensor
tns = torch.from_numpy(arr)

#Repare que o from_numpy preserva os tipos do array no tensor
print(arr)
print(arr.dtype)

print(tns)
print(tns.dtype)


[[0.56609633 0.15275229 0.32262042 0.12363779]
 [0.83392118 0.46467721 0.86129712 0.81214656]
 [0.54594462 0.36343097 0.48743506 0.49715346]]
float64
tensor([[0.5661, 0.1528, 0.3226, 0.1236],
        [0.8339, 0.4647, 0.8613, 0.8121],
        [0.5459, 0.3634, 0.4874, 0.4972]], dtype=torch.float64)
torch.float64


**Convertendo array numpy em tensor**

In [39]:
#Se o array fosse convertido para inteiro o tipo do tensor também seria inteiro
arr = np.random.rand(3,4)
arr = arr.astype(int)
tns = torch.from_numpy(arr)

#convertendo o array numpy em tensor
tns = torch.from_numpy(arr)

#Repare que o from_numpy preserva os tipos do array no tensor
print(arr)
print(arr.dtype)

print(tns)
print(tns.dtype)


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int64
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])
torch.int64


**Tensores pré inicicializados**

In [40]:
#Tensores já inicializados

#Tensor de dimensões 4x2 preenchido com zeros
tns0 = torch.zeros(4,2)

#Tensor de dimensões 2x3 preenchidos com uns
tns1 = torch.ones(2,3)

#Tensor de dimensões 3x3 preenchidos com numeros aleatorios
tnsr = torch.randn(3,3)

print(tns0)
print(tns1)
print(tnsr)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[-0.3328, -0.9173, -1.5337],
        [-0.5290, -0.1940,  0.2813],
        [-1.8499, -0.6573,  0.3111]])


**Convertendo um tensor em array numpy**

In [41]:
#Convertendo um tensor para array numpy
arr = tnsr.data.numpy()
print(arr)
print(type(tnsr))
print(type(arr))

[[-0.3328241  -0.9172647  -1.533739  ]
 [-0.5290364  -0.1939522   0.28128868]
 [-1.8498706  -0.65728164  0.31112045]]
<class 'torch.Tensor'>
<class 'numpy.ndarray'>


**INDEXAÇÃO**

In [42]:
#Indexação

print(tnsr)

#Substituindo o valor da da linha 0 e coluna 2 por -10
tnsr[0,2] = -10
print(tnsr)

#É possível indexar da mesma maneira que um array numpy
#Para acessar apenas ass linhas 0 e 1 do tnsr
print('')
#Repare que o elemento à direita não é inclusivo então se fosse de 0 a 4, seriam as linhas 0,1,2,3
print(tnsr[0:2])

print('')
#Pegando apenas a coluna 2
print(tnsr[:,2])

#Pegando um valor único
print(tnsr[0,2])

tensor([[-0.3328, -0.9173, -1.5337],
        [-0.5290, -0.1940,  0.2813],
        [-1.8499, -0.6573,  0.3111]])
tensor([[ -0.3328,  -0.9173, -10.0000],
        [ -0.5290,  -0.1940,   0.2813],
        [ -1.8499,  -0.6573,   0.3111]])

tensor([[ -0.3328,  -0.9173, -10.0000],
        [ -0.5290,  -0.1940,   0.2813]])

tensor([-10.0000,   0.2813,   0.3111])
tensor(-10.)


**OPERAÇÕES COM TENSORES - SOMA**

In [50]:
#Operações Básicas com Tensores são feitas em ponto a ponto
#É necessário que trabalhemos com tensores de mesma dimensão
#Quando criamos o tns a sua dimensão era 3 x 4
print(tns.shape)

#O tns1 foi criado nas dimensões 2x3
print(tns1.shape)

#Se tentarmos somar os valores do tns com o tns1

#tns_soma = tns + tns1
#The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1
#Vamos então igualar as dimensões 

#o tnsr foi criado com dimensões 3x3
#Então vamos fazer o tns receber o tnsr porém apenas as duas linhas e mantendo as três colunas

tns = tnsr[0:2, :] # 0:2 representa que é para pegar as colunas 0 e 1, e os : no lado direito pegar todas as colunas
tns_soma = tns + tns1

print(tns)
print(tns1)
print(tns_soma)

#Reparem que alguns valores são negativos mas a soma foi feita corretamente

torch.Size([2, 3])
torch.Size([2, 3])
tensor([[ -0.3328,  -0.9173, -10.0000],
        [ -0.5290,  -0.1940,   0.2813]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[ 0.6672,  0.0827, -9.0000],
        [ 0.4710,  0.8060,  1.2813]])


**OPERAÇÕES COM TENSORES - MULTIPLICAÇÃO**

In [52]:
#Se fizermos um tensor multiplicado por outro será feita uma multiplicação ponto a ponto
tns_multi = tns*tns1
print(tns)
print(tns1)
print(tns_multi)

#Se quisermos fazer uma multiplicação de matrizes então é necessário transpor uma das matrizes
#Lembrando que AxB é diferente de BxA

tns_multi_matrizes_real = torch.mm(tns1, tns.T)

print(tns_multi_matrizes_real)

tensor([[ -0.3328,  -0.9173, -10.0000],
        [ -0.5290,  -0.1940,   0.2813]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[ -0.3328,  -0.9173, -10.0000],
        [ -0.5290,  -0.1940,   0.2813]])
tensor([[-11.2501,  -0.4417],
        [-11.2501,  -0.4417]])


**Funções Size e View**

In [62]:
#Similar ao SHAPE
print(tns1.size())
#Mostra as dimensões de um tensor

#Modificando o tamanho de um tensor
tns = torch.randn(2,2,3)
print(tns)

print(tns.size())
#Considerando que temos 2,2,3 como dimensões então temos 12 valores
#É possível achatar esse tensor em uma dimensão apenas com o view
tns = tns.view(12)
print(tns)

#Ao invés de sempre colocar o número de valores presentes no tensor podemos colocar -1
tns = tns.view(-1)
print(tns)

#Como temos 12 valores podemos transformar para por exemplo 4x3, 2x6, entre outros que resultem em 12
tns = tns.view(4,3)
print(tns)

tns = tns.view(2,6)
print(tns)


torch.Size([2, 3])
tensor([[[-1.4461, -0.9871,  0.1950],
         [ 1.7247,  1.1056, -0.2240]],

        [[ 0.7499, -2.1905, -0.4632],
         [-0.9784,  0.2607,  0.6275]]])
torch.Size([2, 2, 3])
tensor([-1.4461, -0.9871,  0.1950,  1.7247,  1.1056, -0.2240,  0.7499, -2.1905,
        -0.4632, -0.9784,  0.2607,  0.6275])
tensor([-1.4461, -0.9871,  0.1950,  1.7247,  1.1056, -0.2240,  0.7499, -2.1905,
        -0.4632, -0.9784,  0.2607,  0.6275])
tensor([[-1.4461, -0.9871,  0.1950],
        [ 1.7247,  1.1056, -0.2240],
        [ 0.7499, -2.1905, -0.4632],
        [-0.9784,  0.2607,  0.6275]])
tensor([[-1.4461, -0.9871,  0.1950,  1.7247,  1.1056, -0.2240],
        [ 0.7499, -2.1905, -0.4632, -0.9784,  0.2607,  0.6275]])


**GPU CAST**

In [1]:
import torch 

tns = torch.randn(10)

if torch.cuda.is_available():
  device = torch.device('cuda')
else:
  device = torch.device('cpu')
print(device)

tns = tns.to(device)
print(tns)

cuda
tensor([ 1.1755,  0.0545,  0.9258,  0.3912,  1.5782, -0.4253, -0.4129, -0.6874,
         2.0569, -0.2264], device='cuda:0')
